In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]='7'
from functools import partial

import torch
from torch.utils.data import DataLoader
from datasets import load_dataset
from gea.self.gpt.s.modeling_gpt import GPTModel, GPTConfig
from gea.self.gpt.s.gpt_executor import GPTTokenizer, DataCollatorwithGPT, preprocess

In [2]:
config = GPTConfig.from_pretrained("/data/lhz/manual/model/3E/gpt/0822")
model = GPTModel(config).to("cuda:0")
tokenizer = GPTTokenizer()

datasets = load_dataset(
    path="json",
    data_files="/data/lhz/manual/datasets/renum/s/train/data.jsonl",
)['train']
datasets = datasets.map(
    partial(preprocess, tokenizer=tokenizer),
    remove_columns=datasets.column_names,
    load_from_cache_file=False,
)
print(datasets[0])
datasets.set_format("torch")
dataloaders = DataLoader(
    datasets,
    batch_size=4,
    collate_fn=DataCollatorwithGPT(),
)

Map:   0%|          | 0/2850407 [00:00<?, ? examples/s]

{'input_ids': [[5, 6, 7, 11, 4, 8, 6, 13, 9, 5, 6, 11, 5, 7, 6, 12]], 'labels': [[2, 4, 1, 2, 11, 9, 5]]}


In [3]:
samples = 1
for i, item in enumerate(dataloaders):
    if i == samples:
        break
    print(item['input_ids'])
    print(item['labels'])
    item = {k:v.to(model.device) for k, v in item.items()}
    outputs = model(**item)

tensor([[ 5,  6,  7, 11,  4,  8,  6, 13,  9,  5,  6, 11,  5,  7,  6, 12,  2,  4,
          1,  2, 11,  9,  5,  0,  0,  0,  0,  0,  0,  0],
        [ 5,  6,  7, 11,  4,  8,  6, 14,  9,  5,  6, 11,  5,  7,  6, 12, 14,  4,
          9, 10, 11,  1, 10,  0,  0,  0,  0,  0,  0,  0],
        [ 5,  6,  7, 11,  4,  8,  6, 15,  9,  5,  6, 11,  5,  7,  6, 12,  4,  9,
          6,  9,  5, 10, 11,  1,  9, 10,  4,  8,  6,  0],
        [ 5,  4,  7, 11,  6, 10,  9, 13,  8,  4,  8, 11,  6,  4,  2, 12,  2,  2,
          8,  5, 11,  2,  3, 10,  0,  0,  0,  0,  0,  0]])
tensor([[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100,    2,    4,    1,    2,   11,    9,    5,    0,
         -100, -100, -100, -100, -100, -100],
        [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100,   14,    4,    9,   10,   11,    1,   10,    0,
         -100, -100, -100, -100, -100, -100],
        [-100, -100, -100, 

In [6]:
print(outputs)

SequenceOutputs(loss=tensor(2.8485, device='cuda:0', grad_fn=<NllLossBackward0>), scores=None, logits=None, hidden_states=None)


In [4]:
# input_ids = torch.tensor([[0,1,2,3,4], [5,0,1,2,3]]).to("cuda:0")
# print(model(input_ids))

In [5]:
print(tokenizer("123+321=", add_special_tokens=False))

tensor([[ 2,  3,  4, 13,  4,  3,  2, 12]])


In [23]:
print(str(float(format(1e-15, ".8f"))))
print(str(float(format(1e15, ".8f"))))
print(f"{1e-16:.8f}")
print(f"{1.5e20:.8f}")
print(f"{123123123123123123423423424.81029380170:.8f}")
print(f"{12.8791827391923:.8f}")
print(format(1123123.981, '.8g'))

0.0
1000000000000000.0
0.00000000
150000000000000000000.00000000
123123123123123124191625216.00000000
12.87918274
1123124


In [1]:
class Experiments:
    records = None
    num = None
    metrics = None
    
    def __init__(self, num, records=None, **kwargs) -> None:
        self.num = num
        self.records = records

    def add(self):
        return 0

    def keys(self):
        # 返回属性名的列表，以便 ** 解包操作使用
        return self.__dict__.keys()

    def __getitem__(self, key):
        # 允许使用 obj[key] 访问属性
        return getattr(self, key)
    
    def __iter__(self):
        # 使实例可以直接通过 ** 解包为字典
        for key, value in self.__dict__.items():
            yield key, value

In [4]:
exp = Experiments(1, 2)
kwargs = {}
dicts = {**kwargs, **exp}
print(dicts)

{'num': 1, 'records': 2}


In [1]:
from typing import Dict
print(isinstance({}, Dict))

True


In [5]:
print([None] * 3)
x = [None] * 3
x[1] = 1
print(x)

[None, None, None]
[None, 1, None]


In [2]:
x = [[]] * 3
x[0].append(1)
x[1].append(2)
print(x)

[[1, 2], [1, 2], [1, 2]]
